input_dir = 'src'
output_dir = 'dist'
output_type = 'compiled'
order_persist = true
with_grpc = true

[protobuf]
version = 'latest'
auto_dl = true
package = 'main'
targets = ['go', 'csharp']


[protobuf.options]
go_package = 'renkei-server/grpc/proto'
csharp_namespace = 'Renkei.Grpc'

[protobuf.target.go]
output_dir = '/../../../server/grpc/proto'