version: '3.1'

services:
  db:
    restart: always
    image: postgis/postgis:16-3.4
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
  
  moria:
    restart: always
    image: ghcr.io/sevenitynet/moria:latest
    environment:
      AUTH_TOKEN: ${MORIA_AUTH_TOKEN}
      CORS_ALLOWED_ORIGINS: '*'
    ports:
      - 1980:1980
    
volumes:
  redis: {} 
  db: {}
